### ISSUE TITLE
Stream is already completed, no further calls are allowed

### ISSUE THREAD

**Issue by thing72** [thing72/libgdx-game#323]

**Comment by thing72** [comment]
Exception in thread "Timer-0" java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:363)
	at core.networking.client.ClientNetworkHandle.send(ClientNetworkHandle.java:100)
	at core.networking.events.consumer.client.outgoing.PingRequestOutgoingConsumerClient.accept(PingRequestOutgoingConsumerClient.java:18)
	at core.networking.events.consumer.client.outgoing.PingRequestOutgoingConsumerClient.accept(PingRequestOutgoingConsumerClient.java:10)
	at core.common.events.EventService.lambda$fireEvent$1(EventService.java:40)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at core.common.events.EventService.fireEvent(EventService.java:40)
	at core.networking.ping.PingService.run(PingService.java:91)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
